### ISSUE TITLE
Cannot read property 'preference' of undefined inside Storybook

### ISSUE THREAD

**Issue by ManUtopiK** [nuxt-community/color-mode-module#69]
### Version
@nuxtjs/color-mode: ^2.0.3
nuxt: ^2.14.12
@nuxtjs/storybook: ^3.3.1

### Steps to reproduce
Install nuxt with @nuxtjs/color-mode and @nuxtjs/storybook.

### What is actually happening?

I run nuxt as `target: static`. Everything works fine with `yarn dev`.
I can launch Storybook and got it at localhost:3003, but inside the main frame of Storybook, there is this error:
`Cannot read property 'preference' of undefined`.

I tried everything related in #21 and #25 without success...

**Comment by ManUtopiK** [comment]
I think I just fixed this issue, but I made many change on the storybook config, so I'm not sure how I did...
I set a custom storybook config as [explained here](https://storybook.nuxtjs.org/manual-setup).

But maybe it's work just only with this file `.storybook/preview-head.html`:
```
<script>
  var data = {}
  window['__NUXT_COLOR_MODE__'] = {
    preference: 'light',
  }
</script>
```

**Comment by farnabaz** [comment]
`@nuxtjs/storybook` executes plugin scripts after the plugin import and this cause the issue. And ` color-mode` uses global variable on import. The leads to `undefined` error.

**Comment by kgnfth** [comment]
@Atinux i have the same issue after upgrading from 2.0.5 to 2.0.7

my settings is 
nuxt.config.js

```js
colorMode: {
  storageKey: 'color-mode',
  preference: 'system',
  fallback: 'dark',
  classSuffix: '',
}
```

and in my tailwind.config.js i have

`darkMode: 'class'`

**Comment by kgnfth** [comment]
> Hi @kgnfth
> 
> Please use `2.0.8`, small mistake sorry about this.

Thx it works 💙

**Comment by BennaceurHichem** [comment]
I'm having the same problem, I used the 2.0.8 version but the error still occurs in Storybook, any idea?

**Comment by BennaceurHichem** [comment]
Yes I did, I was workinf with 2.0.10, then I downgrade and same thing. This error was gone when I applied what @ManUtopiK  mention

**Comment by gimyboya** [comment]
@Atinux is there a cleaner way as to not have to eject and keep using the module way of doing things with nuxtjs. while the solution provided by @ManUtopiK works it forces us to have the config in the `.storybook` folder.

**Comment by farnabaz** [comment]
@gimyboya  Using `color-mode@v2.0.8` + `nuxt-storybook > 4.0.0` should work without any issues.

New versions of module is not compatible with Storybook because it uses `vue-renderer` hook to inject script and `nuxt-storybook` does not support renderer hooks. https://github.com/nuxt-community/color-mode-module/blob/master/lib/module.js#L31
